#!/bin/bash

echo "installing dotfiles"
cp bspwm/bspwmrc ~/.config/bspwm
cp sxhkd/sxhkdrc ~/.config/sxhkd
cp alacritty/alacritty.yml ~/.config/alacritty
cp -r nvim/* ~/.config/nvim
cp tmux/.tmux.conf ~/
cp compton/.compton.conf ~/.config

cp -r polybar ~/.config

cp gitconfig/.gitconfig ~/
cp xinitrc/.xinitrc ~/
cp Xresources/.Xresources ~/
cp zshrc/.zshrc ~/
sudo cp pasta /usr/lib/urxvt/perl/pasta

echo "done."
