#! /bin/sh
bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		     7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d term web code music chat vm I II

bspc rule -a icefox desktop=^1
bspc rule -a urxvt state=floating
bspc rule -a URxvtQuake sticky=on floating=on

bspc config focus_follows_pointer true

wmname LG3D 
